pipeline {
    agent {
        docker {
            // Feel free to change the image for your project. Image taken from: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node18.6.0-chrome105-ff104
            image 'cypress/base:18.6.0'
        }
    }
}